### PR TITLE
Add check length function to model class

### PR DESCRIPTION
**Pull request by JohnyFW**
Added function to check the length of a varchar field.
function that simplifies the test method of the models

### CODE REVIEW

**Comment by NeoRazorX** [comment]
ModelClass is so big, and this function seems unhelpful in this case.

**Comment by JohnyFW** [comment]
ok

**Comment by rsanjoseo** [comment]
I would check the length of both text and numeric field in the model.

If the information is defined in the XML file, the generic test ) could already perform the verification.

As I mentioned in Tenerife, I would ALSO add the check in the html code to filter from the browser (if available).

**Comment by JohnyFW** [comment]
The objective is to simplify the final models, especially the test before recording. for example:

```
$error = $this->errorInStrLen($this->nombre, 'name', 100, 1) 
      || $this->errorInStrLen($this->cifnif, 'cifnif', 30, 1) 
      || $this->errorInStrLen($this->ciudad, 'city', 100, 0);

return !$error && parent::test();
```

**Pull request closed without merging**
